function calculate()
{
            var prices = new Array(31);
            var quantities=new Array(31);
            prices[0]=document.getElementById("price1").value;
            quantities[0]=document.getElementById("quantity1").value;
            console.log(prices[0] + " "+ quantities[0]);
            prices[1]=document.getElementById("price2").value;
            quantities[1]=document.getElementById("quantity2").value;
            console.log(prices[1]);
            prices[2]=document.getElementById("price3").value;
            quantities[2]=document.getElementById("quantity3").value;
            console.log(prices[2]);
            prices[3]=document.getElementById("price4").value;
            quantities[3]=document.getElementById("quantity4").value;
            console.log(prices[3]);
            prices[4]=document.getElementById("price5").value;
            quantities[4]=document.getElementById("quantity5").value;
            console.log(prices[4]);
            prices[5]=document.getElementById("price6").value;
            quantities[5]=document.getElementById("quantity6").value;
            console.log(prices[5]);
            prices[6]=document.getElementById("price7").value;
            quantities[6]=document.getElementById("quantity7").value;
            console.log(prices[6]);
            prices[7]=document.getElementById("price8").value;
            quantities[7]=document.getElementById("quantity8").value;
            console.log(prices[7]);
            prices[8]=document.getElementById("price9").value;
            quantities[8]=document.getElementById("quantity9").value;
            console.log(prices[8]);
            prices[9]=document.getElementById("price10").value;
            quantities[9]=document.getElementById("quantity10").value;
            console.log(prices[9]);
            prices[10]=document.getElementById("price11").value;
            quantities[10]=document.getElementById("quantity11").value;
            console.log(prices[10]);
            prices[11]=document.getElementById("price12").value;
            quantities[11]=document.getElementById("quantity12").value;
            console.log(prices[11]);
            prices[12]=document.getElementById("price13").value;
            quantities[12]=document.getElementById("quantity13").value;
            console.log(prices[12]);
            prices[13]=document.getElementById("price14").value;
            quantities[13]=document.getElementById("quantity14").value;
            console.log(prices[13]);
            prices[14]=document.getElementById("price15").value;
            quantities[14]=document.getElementById("quantity15").value;
            console.log(prices[14]);
            prices[15]=document.getElementById("price16").value;
            quantities[15]=document.getElementById("quantity16").value;
            console.log(prices[15]);
            prices[16]=document.getElementById("price17").value;
            quantities[16]=document.getElementById("quantity17").value;
            console.log(prices[16]);
            prices[17]=document.getElementById("price18").value;
            quantities[17]=document.getElementById("quantity18").value;
            console.log(prices[17]);
            prices[18]=document.getElementById("price19").value;
            quantities[18]=document.getElementById("quantity19").value;
            console.log(prices[18]);
            prices[19]=document.getElementById("price20").value;
            quantities[19]=document.getElementById("quantity20").value;
            console.log(prices[19]);
            prices[20]=document.getElementById("price21").value;
            quantities[20]=document.getElementById("quantity21").value;
            console.log(prices[20]);
            prices[21]=document.getElementById("price22").value;
            quantities[21]=document.getElementById("quantity22").value;
            console.log(prices[21]);
            prices[22]=document.getElementById("price23").value;
            quantities[22]=document.getElementById("quantity23").value;
            console.log(prices[22]);
            prices[23]=document.getElementById("price24").value;
            quantities[23]=document.getElementById("quantity24").value;
            console.log(prices[23]);
            prices[24]=document.getElementById("price25").value;
            quantities[24]=document.getElementById("quantity25").value;
            console.log(prices[24]);
            prices[25]=document.getElementById("price26").value;
            quantities[25]=document.getElementById("quantity26").value;
            console.log(prices[25]);
            prices[26]=document.getElementById("price27").value;
            quantities[26]=document.getElementById("quantity27").value;
            console.log(prices[26]);
            prices[27]=document.getElementById("price28").value;
            quantities[27]=document.getElementById("quantity28").value;
            console.log(prices[27]);
            prices[28]=document.getElementById("price29").value;
            quantities[28]=document.getElementById("quantity29").value;
            console.log(prices[28]);
            prices[29]=document.getElementById("price30").value;
            quantities[29]=document.getElementById("quantity30").value;
            console.log(prices[29]+" "+ quantities[29]);
            prices[30]=document.getElementById("price31").value;
            quantities[30]=document.getElementById("quantity31").value;
            console.log(prices[30]);


    var sum=0;
    for(var i=0;i<31;i++)
    {
        sum=sum+(prices[i]*quantities[i]);
    }
    var currency="¥";
    var withoutcom=(sum*0.9725);
    document.getElementById("result").innerHTML=sum+" "+currency.charAt(1);
    var youget=" (You get : " + withoutcom +" "+currency.charAt(1)+")";
    document.getElementById("youget").innerHTML=youget;
}